language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm run build
after_success:
  - npm run deploy
  - npx travis-deploy-once "npx semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
