language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
    - npm run build
    - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
